backend:
  name: github
  repo: ashutoshbibyan/ashutoshbibyan.github.io
  branch: decap-cms-init
  # Make sure "https://" is at the very beginning!
  base_url: https://decap-cms-oauth.ashutosh2013official.workers.dev 
  auth_endpoint: /auth

# Use the paths relative to the root of your GITHUB REPO
media_folder: "src/assets/images/blog" 
public_folder: "/src/assets/images/blog" # Absolute path from site root

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Summary", name: "description", widget: "text" }
      - { label: "Featured Image", name: "heroImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }